sudo: required
os: linux
dist: xenial
language: generic
services: 
   - docker
before_install:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker build -t nasri/snapp:v1 -f application/v1.0.0/Dockerfile .
   - docker build -t nasri/snapp:v2 -f application/v2.0.0/Dockerfile .
   - docker build -t nasri/snapp:v3 -f application/v3.0.0/Dockerfile .
   - docker build -t nasri/snapp:v4 -f application/v4.0.0/Dockerfile .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: main  
    
